algoritmo "semnome"

var
time:caracter
inicio
escreval ("Digite o nome de um time: ")
leia(time)
escolha time
 caso "so Paulo","Palmeira","Corinthians"
 escreval("VOCE ESCOLHEU UM TIME PAULISTA")
  caso "Flamengo","Vasco","BOTAFOGO"
 escreval("VOCE ESCOLHEU UM TIME CARIOCA")
  caso "Gremio","cruzeiro","inter"
 escreval("VOCE ESCOLHEU UM TIME SULISTA")
 outrocaso
 escreval ("Time invalido")
 fimescolha

 
fimalgoritmo



